name: Release Image
on:
  push:
    branches:
      - main
jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: cachix/install-nix-action@v24
          with:
            extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
            github_access_token: ${{ secrets.GITHUB_TOKEN }}
        - name: Build
          run: nix build .#digitalocean-image
        - name: Push to GitHub releases
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            ./.github/scripts/release.py
